### ISSUE TITLE
Luar Biasa Playlistnyna; izin Request Boleh Bang?

### ISSUE THREAD

**Issue by HexSorcerer** [mimipipi22/lalajo#8]
permisi bang, jika waktunya luang dan berkenan apakah boleh izin  request vod film-film indonesia bang? kayak Ayat-Ayat Cinta 3, Badarawuhi, dkk.
terima kasih

**Comment by mimipipi22** [comment]
Buka di link ini bang:    https://ww03.pencurimovie.bond/country/indonesia/
